//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Automobil> Automobil { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<MarkaAutomobila> MarkaAutomobila { get; set; }
        public DbSet<ModelAutomobila> ModelAutomobila { get; set; }
        public DbSet<ModelTip> ModelTip { get; set; }
        public DbSet<Rezervacija> Rezervacija { get; set; }
        public DbSet<Slika> Slika { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipAutomobila> TipAutomobila { get; set; }
        public DbSet<TipKorisnika> TipKorisnika { get; set; }
    }
}
